Stronger ESLint (no longer rely on TSDX for linting)
opendatasoft/ods-dataviz-sdk pull request #103
Opened 2022-08-26 16:19 UTC by wmai

// TODO: Describe changes

2022-08-30 16:23 UTC, RafaelSzmarowski approved these changes
LGTM ! Nice work ! 

As a reminder, even if it's not blocking for now, I have this warning in my console :  

```
Cannot find type definition file for 'jest'.
The file is in the program because:
Entry point of type library 'jest' specified in compilerOptions
```

2022-09-02 15:06 UTC, etienneburdet requested changes
Thank you for doing this, it's a real chore… 💪 It seems to be mostly working, although I don't have eslint error in Svelte files in my ide (but they are corrected on save…). I'll work on that.

My main suggestion would be to try to factor as much as we can for dev config. I think we could have a top level tsconfig with [this technique](https://blog.logrocket.com/setting-up-monorepo-with-lerna-typescript/), we can have a base eslintconfig that we import in each package and then extend (most of it is shared), move all [the tasks (lint, tests etc.) to top level](https://lerna.js.org/docs/faq#root-packagejson) and maybe use hoisting for devDependencies. What do you think?

2022-09-08 08:44 UTC, wmai commented on packages/api-client/test/client-node.test.ts
> +/* eslint-disable no-new */
Actually I think we want to catch the error when an instance of ApiClient is created here. If we create the instance outside the `expect` block, we won't be able to catch the error.

2022-09-08 08:44 UTC, wmai commented on packages/api-client/test/client-node.test.ts
> +/* eslint-disable no-new */
Actually I think we want to catch the error when an instance of ApiClient is created here. If we create the instance outside the `expect` block, we won't be able to catch the error.

2022-09-08 08:44 UTC, wmai commented on packages/api-client/package.json
>          "prepare": "tsdx build",
I'm sorry there must be something I didn't understand about Lerna. Each of these scripts (although named the same) are different in each package. How would you move them to the parent `package.json`?

2022-09-08 08:46 UTC, wmai commented
Thank you very much for the thorough review @etienneburdet 🙏

> My main suggestion would be to try to factor as much as we can for dev config. I think we could have a top level tsconfig with [this technique](https://blog.logrocket.com/setting-up-monorepo-with-lerna-typescript/), we can have a base eslintconfig that we import in each package and then extend (most of it is shared), move all [the tasks (lint, tests etc.) to top level](https://lerna.js.org/docs/faq#root-packagejson) and maybe use hoisting for devDependencies. What do you think?

Yes, I also wanted to have a common `tsconfig` configuration because the different packages share many properties. But the problem is that you can only inherit one file via the `extends` parameter, and the `visualizations` package already inherits ``@tsconfig/svelte/tsconfig.json``.

And regarding the ESLint configuration sharing, I think it would indeed be nice to try to factor that. But we will have to get rid of TSDX in the `visualizations-react` package first.

2022-09-08 08:51 UTC, etienneburdet commented
👌However, thinking about it, we might want to have a separate PR for the factoring. First remove tsdx one package at a time, then be smart 😂

2022-09-08 10:20 UTC, merged

2022-09-08 11:19 UTC, etienneburdet commented on packages/api-client/test/client-node.test.ts
> +/* eslint-disable no-new */
ha yes, and const xxx = new ApiClient, will raise an "unused". Not worth it indeed…