[sc-37353] Feature: Don't render world copies
opendatasoft/ods-dataviz-sdk pull request #133
Opened 2022-12-06 10:14 UTC by wmai

## Summary

The goal for this PR is to prevent multiple copies of the world to be rendered side by side.

(Internal for Opendatasoft only) Associated Shortcut ticket: [sc-37353](https://app.shortcut.com/opendatasoft/story/37353).

**The result:**
<img width="711" alt="Screenshot 2022-12-06 at 11 14 04" src="https://user-images.githubusercontent.com/8331608/205883236-9a51cf66-6ac2-404e-a151-8d3a69de6c2e.png">

### Changes

[setRenderWorldCopies](https://docs.mapbox.com/mapbox-gl-js/api/map/#map#setrenderworldcopies) set to `false` when the map initialize.

#### Breaking Changes

_describe the changes that are not backward compatible_

### Changelog

Prevent multiple copies of the world to be rendered side by side.

## Review checklist

- [ ] Description is complete
- [ ] 2 reviewers (1 if trivial)
- [ ] Tests coverage has improved
- [ ] Code is ready for a release on NPM

2022-12-23 16:05 UTC, RafaelSzmarowski requested changes
Nice improvements ! I have only one code remark and one question on the `valueFormatter` option that needs, in my opinion, to be discussed unless I've missed something but nothing huge and overall it works great. I've tested the `renderWorldCopies` and the legend position  👍

2022-12-23 16:05 UTC, RafaelSzmarowski commented on packages/visualizations/src/components/Map/types.ts
> +    valueFormatter?: (value: number) => string;
It's a bonus but it would be nice to have a storybook story to illustrate the use of this new option 🏅

2022-12-28 13:53 UTC, wmai commented on packages/visualizations/src/components/Map/WebGl/MapRender.svelte
> +        map.setRenderWorldCopies(false);
I didn't realised that this prop could be initialised this way 🤦‍♂️ Thanks @RafaelSzmarowski

2022-12-28 13:56 UTC, wmai commented on packages/visualizations/src/components/Map/types.ts
> +    valueFormatter?: (value: number) => string;
Indeed very good catch! The changes have been made in [this PR](https://github.com/opendatasoft/ods-dataviz-sdk/pull/131).

2022-12-30 15:52 UTC, closed without merging