Run chromatic on branch ready
opendatasoft/ods-dataviz-sdk pull request #199
Opened 2023-10-11 15:03 UTC by etienneburdet

## Summary

The goal for this PR is to run chromatic only when the branch is ready is for review. The idea is that we would keep branches in draft state for longer and only turn them ready relatively late. It's always possible to discuss drafts or trigger manual runs.

For now:
- API client code coverage run for each commit where api-client files has been edited
- Viz CI run for each commit in a PR. Chromatic job run only when test and lint jobs passed with the PR state as 'ready for review'

Other possibilities include : run on label change, run on review request… for exemple.

**Review workflow**: 
- Create a new branch from this branch
- Add commits that should break the CI (test or lint)
- Open a PR in draft (CI should fail and chromatic job not run)
- Fix the CI, chromatic job should still not run
- Make the PR ready for review. CI should re-run with now chromatic running
- Make a commit that break lint or test. CI should fail, chromatic job should not run

2023-12-29 10:48 UTC, etienneburdet commented
Ok this PR is officially "ready for review" (I had to turn it on and off to test stuff).  The conditional trigger of Chromatic on lint seems to work well.

I didn't manage to have the `if` working properly on this branch, for not running on draft. It seems it only works if the PR opened as draft, but if it has been turned on/off it still runs everything 🤷

2024-01-10 13:29 UTC, KevinFabre-ods requested changes
Thanks for taking care of that:

Chromatic deployment: 
- is blocked when at least one test or lint job fails ✅ 
- is run only when the PR is review for review 🚫

Don't know why but the` if: github.event.pull_request.draft == false` condition doesn't block the job

2024-01-10 13:29 UTC, KevinFabre-ods commented on .github/workflows/visualizations.yml
> +    if: github.event.pull_request.draft == false
Still run even if the PR in draft mode, see https://github.com/opendatasoft/ods-dataviz-sdk/pull/214

2024-01-10 14:24 UTC, KevinFabre-ods commented
In the viz workflow by replacing the 
```
on: 
 - push 
```
by
``` 
on: 
   pull_request:
      types:
        - opened
        - synchronize
        - reopened
        - ready_for_review
```

it works (https://github.com/opendatasoft/ods-dataviz-sdk/pull/214)

to access `github.event.pull_request.draft` we need to react to the pull_request event, that what we are doing by adding the on: pull_request

2024-01-10 14:58 UTC, etienneburdet commented
Ha nice, I think I lacked the `synchronize` in the early version for it to react to push. I'll just rebase to erase test commits before merging.

2024-01-10 16:53 UTC, KevinFabre-ods commented
I already rebased and erased tests commits => https://github.com/opendatasoft/ods-dataviz-sdk/pull/199/commits/73a3814cf26c7bb0cca03928a55ee1e4499f8a0b

2024-01-10 17:24 UTC, KevinFabre-ods approved these changes
Looks good to me now

@wmai you have review instructions in the PR description 😉

2024-01-11 08:31 UTC, wmai approved these changes
I've tried all sorts of choreographies, the CI behaves as expected, very good job, thank you for this work. 🙏

2024-01-11 08:44 UTC, merged