Increase style consistency on maps
opendatasoft/ods-dataviz-sdk pull request #216
Opened 2024-01-15 09:01 UTC by cybervinvin

## Summary

The goal for this PR is to harmonise the style of the cursor between all the SDK maps, to bring consistency to the use of the SDK.

(Internal for Opendatasoft only) Associated Shortcut ticket: [sc-45175](https://app.shortcut.com/opendatasoft/story/45175/sdk-choropleth-map-update-cursor-style).

### Changes

Update pointer styles when it's over the map and when it's start to drag the map.

#### Breaking Changes

None...I hope

### Changelog

None

## Open discussion

Always welcome

## To be tested

Simply test hovering and dragging a map in a studio page.

## Review checklist

- [X] Description is complete
- [X] Commits respect the [Conventional Commits Specification](https://github.com/opendatasoft/ods-dataviz-sdk/blob/main/CONTRIBUTING.md#commit-messages)
- [X] 2 reviewers (1 if trivial)
- [ ] Tests coverage has improved
- [ ] Code is ready for a release on NPM

2024-01-15 13:03 UTC, KevinFabre-ods requested changes
https://github.com/opendatasoft/ods-dataviz-sdk/assets/117300300/b2785a2e-60d6-40f1-8dff-c732539a15de

First hover on the map: cursor is grab and after a move, the cursor is default. 

This isn't the same behavior as POI Maps

https://github.com/opendatasoft/ods-dataviz-sdk/assets/117300300/a9f989c5-b6cb-4560-a744-bc81a30ef875

The hover cursor should always be of the default style.
For the POI Maps we add a bit of CSS to handle the default state: 

https://github.com/opendatasoft/ods-dataviz-sdk/blob/main/packages/visualizations/src/components/MapPoi/MapRender.svelte#L115-L117

2024-01-17 13:50 UTC, RafaelSzmarowski reviewed
LGTM ! Seems like everything works as expected and that we don't need to have a HOVER state for the choropleth, so it seems weird to have it in the CURSOR constant here. IMO we should remove it if it is not used or already factor for both maps ? But it won' t be too difficult to do it later so the final decision can be up to you

2024-01-17 13:56 UTC, RafaelSzmarowski approved these changes

2024-01-17 16:27 UTC, KevinFabre-ods approved these changes
LGTM ✔️

2024-01-23 15:08 UTC, merged