Migrate to node 20
opendatasoft/ods-dataviz-sdk pull request #228
Opened 2024-03-08 13:15 UTC by etienneburdet

- @opendatasoft/visualizations-react@0.21.0
 - @opendatasoft/visualizations@0.21.0

## Summary

The goal for this PR is to upgrade the engines requirements for  node.

### Changes
Disabled rollup visualizer plugin to avoid migrating the full stack. Else I just upgrade all references to nodes >18 (current LTS) and checked it works with node 20.

#### Breaking Changes

_describe the changes that are not backward compatible_

### Changelog

_short sentence to serve as a public changelog:_

For a bug: "We fixed a bug in the Map component: Middle-Earth's vector tiles are now available."

For a new feature: "In the Map component: It's now possible to display the route of Frodo's journey from Hobbiton to Mount Doom."

2024-03-18 09:11 UTC, KevinFabre-ods commented
> So last part of the update: `@mapbox/geo-viewport` was crashing and is pretty much abandonned. I decided to drop the computation in favor of a props. Now, there is another way to compute the max zoom as we did with `@mapbox/geo-viewprot` but with `turf` and it would look something like this:
> 
> ```
> const bboxDiagonal = turf.length(turf.bboxPolygon(bounds));
> const screenDiagonal = Math.sqrt(Math.pow(containerWidth, 2) + Math.pow(containerHeight, 2));
> const screenDiagonalMeters = screenDiagonal * 0.0254; // approx ratio for PPI to meters
> const zoom = Math.log2(screenDiagonalMeters / bboxDiagonal) + 8;
> ```
> 
> My idea though, was to implement that in the Studio (leaving the option to pass it more directly if needed). Another option in the Studio would be to pass "hard" values for goeref for exemple. What do you think @KevinFabre-ods ?
> 
> Other differences in chromatic should be really minor.

Looks this comment doesn't fit with the changes. Currently `@mapbox/geo-viewport` has been replaced with `placemark/geo-viewport`. The maxZoom props defined in `ChoroplethVectorTiles.svelte` doesn't do anything as `MapRender` doesn't have a `maxZoom` prop declaration.

2024-03-18 14:41 UTC, etienneburdet commented
> > So last part of the update: `@mapbox/geo-viewport` was crashing and is pretty much abandonned. I decided to drop the computation in favor of a props. Now, there is another way to compute the max zoom as we did with `@mapbox/geo-viewprot` but with `turf` and it would look something like this:
> > ```
> > const bboxDiagonal = turf.length(turf.bboxPolygon(bounds));
> > const screenDiagonal = Math.sqrt(Math.pow(containerWidth, 2) + Math.pow(containerHeight, 2));
> > const screenDiagonalMeters = screenDiagonal * 0.0254; // approx ratio for PPI to meters
> > const zoom = Math.log2(screenDiagonalMeters / bboxDiagonal) + 8;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > My idea though, was to implement that in the Studio (leaving the option to pass it more directly if needed). Another option in the Studio would be to pass "hard" values for goeref for exemple. What do you think @KevinFabre-ods ?
> > Other differences in chromatic should be really minor.
> 
> Looks this comment doesn't fit with the changes. Currently `@mapbox/geo-viewport` has been replaced with `placemark/geo-viewport`. The maxZoom props defined in `ChoroplethVectorTiles.svelte` doesn't do anything as `MapRender` doesn't have a `maxZoom` prop declaration.
> 
> Also it's a bit weird that we don't get any eslint error we use a set a prop that doesn't exist. Maybe we should update` eslint-plugin-svelte3` with https://github.com/sveltejs/eslint-plugin-svelte as it is deprecated

Ha sorry, I thought I had posted a comment about that: I dropped the turf idea, it was missing some key projection stuff. And in the meantime I found a maintained fork, which will do for this update. `maxZoom` should go indeed.

2024-03-19 12:29 UTC, KevinFabre-ods reviewed
GG for the migration 👏 

I left some comments to have explanation on specific topics, but nothing blocking

2024-03-21 17:09 UTC, etienneburdet commented on packages/visualizations/src/components/Chart/Chart.svelte
> +            style="--aspect-ratio: {defaultValue(options.aspectRatio, 4 / 3)}"
`aspectRatio` and `maintainAspectRatio` are for the canvas but the not the container. And now ChartJS relies on listening to the parent container size change, so without that charts don't resize without the window now.
See https://www.chartjs.org/docs/latest/configuration/responsive.html

2024-03-21 17:23 UTC, etienneburdet commented on packages/visualizations-react/.storybook/main.js
Yes, that's probably better, I didn't know about it. This is one is basically copy paste from storybook doc.

Not sure how much we want to dig into Nx though. Right now it's wrapped by Lerna, but we don't really have a Nx conf. Do we want to dive into that?

2024-04-04 08:48 UTC, KevinFabre-ods requested changes
A bit of clean up to do around the package.json and yml files are we should be good 😄

2024-04-04 08:48 UTC, KevinFabre-ods commented on packages/visualizations/src/components/Chart/Chart.svelte
> +            style="--aspect-ratio: {defaultValue(options.aspectRatio, 4 / 3)}"
I see, it's a bit weird to use twice the aspect ratio but it doesn't seem we can do differently.

.`maintainAspectRatio` and `responsive` are `true` by default I think we can remove: 
```js
// Chart.svelte
chartOptions.maintainAspectRatio = true;
chartOptions.responsive = true;
```

2024-04-04 08:48 UTC, KevinFabre-ods commented on packages/visualizations-react/.storybook/main.js
Yes but later (in a future story) ;)

2024-04-04 08:56 UTC, etienneburdet commented on .github/workflows/visualizations.yml
> +        run: npm ci --workspaces --include-workspace-root --install-links
Actually, I don't think we even nedd the install step anymore 🤔 Could be in a `build` script indeed

2024-04-05 11:19 UTC, etienneburdet commented
I added an `npm run build-ci` script to install/build for all tasks, tell me what you think about it!

2024-04-12 09:14 UTC, KevinFabre-ods commented on packages/visualizations-react/package.json
> +        "@opendatasoft/visualizations": "^0.21.1-beta.0",
Did the update here
https://github.com/opendatasoft/ods-dataviz-sdk/pull/228/commits/f76087de35ffed0e1e768e4da654857653d5fc50

2024-04-12 09:15 UTC, KevinFabre-ods approved these changes
Looks fine, I just added a [commit](https://github.com/opendatasoft/ods-dataviz-sdk/pull/228/commits/f76087de35ffed0e1e768e4da654857653d5fc50) to restore the good packages versions. Since your started this branch, we had some releases

2024-04-12 09:17 UTC, merged