feat: add an empty state for the table
opendatasoft/ods-dataviz-sdk pull request #247
Opened 2024-06-14 13:49 UTC by etienneburdet

## Summary

The goal for this PR is to add a small phrase to indicate that no records were found—but appart from that the table hasn't crashed.

(Internal for Opendatasoft only) Associated Shortcut ticket: [sc-50771](https://app.shortcut.com/opendatasoft/story/50771).

### Changes
I added another alternative render for the body, similar to the loading state.

I could have made it into it's own component, but I don't find the `Body.svelte` too cluttered for now. I'm totally open to it though.

2024-06-17 12:38 UTC, KevinFabre-ods requested changes
Look goods, we just need to extract it from the options in `TableCard.svelte`

2024-06-17 12:38 UTC, KevinFabre-ods commented on packages/visualizations-react/stories/Table/Table.stories.tsx
> +    options: { ...options, emptyStateLabel: 'Neniuj registroj trovitaj...' },
Story should show 'Neniuj registroj trovitaj...'

Prop drilling to `Body.svelte` is missing

2024-06-24 08:00 UTC, KevinFabre-ods commented
@etienneburdet With the latest merges, we have some conflicts.
Could you please resolve them, so that we can do a release ? 

Thanks

2024-06-24 08:55 UTC, KevinFabre-ods approved these changes
LGTM ✅  

We just lost the loading story during the merge

2024-06-24 08:55 UTC, KevinFabre-ods commented on packages/visualizations-react/stories/Table/Table.stories.tsx
> +    options: { ...options, emptyStateLabel: 'Neniuj registroj trovitaj...' },
We lost the "loading state" story

2024-06-25 07:40 UTC, etienneburdet commented on packages/visualizations-react/stories/Table/Table.stories.tsx
> +    options: { ...options, emptyStateLabel: 'Neniuj registroj trovitaj...' },
should be good 🙈

2024-06-25 07:48 UTC, KevinFabre-ods commented on packages/visualizations/src/components/Table/Body.svelte
> +    {/if}
We need to display this UI when `isLoading` is true
![image](https://github.com/opendatasoft/ods-dataviz-sdk/assets/117300300/8ed9ac24-5a3c-45e9-b1cd-71ebfc78a5d8)

Thanks to the loading story 😝

2024-06-25 16:16 UTC, etienneburdet reviewed
haaaa indeed, pushed a bit too fast.

2024-06-26 09:35 UTC, KevinFabre-ods approved these changes
LGTM

2024-06-26 09:36 UTC, merged