Add direction on the `Table` component
opendatasoft/ods-dataviz-sdk pull request #249
Opened 2024-06-21 07:55 UTC by cybervinvin

## Summary

The goal for this PR is to change the reading direction in the `Table` component depending on a property.

(Internal for Opendatasoft only) Associated Shortcut ticket: [sc-48044](https://app.shortcut.com/opendatasoft/story/48044/sdk-add-direction-rtl-to-table).

### Changes

Add a new property `direction` for `TableCard`.
Use 2 new stores: `direction` and `isRtl` to propagate the property in the component tree.

#### Breaking Changes

None

### Changelog

In the Table component: It's now possible to change the reading direction depending on the locale.

## To be tested

In storybook: change the `direction` value in `options`

## Review checklist

- [X] Description is complete
- [] Commits respect the [Conventional Commits Specification](https://github.com/opendatasoft/ods-dataviz-sdk/blob/main/CONTRIBUTING.md#commit-messages)
- [ ] 2 reviewers (1 if trivial)
- [ ] Tests coverage has improved
- [ ] Code is ready for a release on NPM

2024-06-21 12:39 UTC, KevinFabre-ods reviewed
I have left some general comments.

As we discussed, we are awaiting confirmation on how the direction should be handled for this component:
 - Based on the HTML attribute `dir`
 - Or by using a `direction` prop

In my opinion, we should rely solely on the HTML attribute `dir` to avoid the complexity of managing potential difference between the `dir` attribute and the `direction` prop.

2024-06-21 12:39 UTC, KevinFabre-ods commented on packages/visualizations-react/stories/Table/options.ts
<img width="1090" alt="image" src="https://github.com/opendatasoft/ods-dataviz-sdk/assets/117300300/137cce4c-69a5-4312-8d05-eac1697b5759">

title, subtitle and pagination are not in RTL configuration.

To align title and subtitle to the right we need to pass a prop to the `Card` component. I really don't know if we want to do that.

2024-06-21 12:39 UTC, KevinFabre-ods commented on packages/visualizations-react/stories/Table/options.ts
You can add this storybook addon (https://storybook.js.org/addons/storybook-addon-rtl/) to test components based on the page direction

2024-06-21 12:39 UTC, KevinFabre-ods commented on packages/visualizations/src/components/Table/Cell/Cell.svelte
> +    }
Using `css` to set direction seems not recommended

https://www.w3.org/International/questions/qa-html-dir.en.html#no_css

2024-06-21 12:39 UTC, KevinFabre-ods commented on packages/visualizations/src/components/Table/types.ts
> +    direction?: string;
```suggestion
    direction?: 'ltr' | 'rtl'; 
```
To be more precise

2024-06-24 15:36 UTC, etienneburdet requested changes
I might be missing some bits, but I think `<table dir={dir} />` does most of the heavy work, both for columns ordering, cell rendering, a11y etc. and that we might just want to force some cells to always left/right (probably numbers, url, geo)

2024-06-24 15:36 UTC, etienneburdet commented on packages/visualizations/src/components/Table/Table.svelte
> +    }
I think `<table dir="rtl">` has more benefits (a11y, send to cells etc.)

2024-06-24 15:36 UTC, etienneburdet commented on packages/visualizations/src/components/Table/Cell/Cell.svelte
> +    :global(.ods-dataviz--default td.rtl-direction) {
From my tries, if we have `<table dir="rtl">` then text in td will be rtl. We might want to force ltr for some formats though (number, maybe URL).

2024-06-24 15:36 UTC, etienneburdet commented on packages/visualizations/src/components/Table/Headers/Headers.svelte
> +    }
```suggestion
    :global(.ods-dataviz--default table[dir="rtl"] th) {
        text-align: right;
    }
```

2024-06-24 15:36 UTC, etienneburdet commented on packages/visualizations/src/components/Table/TableCard.svelte
>      $: loadingRowsNumber = isLoading ? defaultLoadingRowsNumber : null;
You could do with only one store here, $dir is never used again
```suggestion
    $: {
        const dir = direction || (RTL_LANGUAGES_CODE.includes($locale) ? 'rtl' : 'ltr');
        $isRtl = dir === 'rtl';
    }
```

2024-06-24 15:36 UTC, etienneburdet commented on packages/visualizations/src/components/Table/constants.ts
> +] as string[];
as const probably (it's already string[]). I didn't find a good way to fetch this list from somewhere reliable. At the very list we want a source link as comment.

2024-06-24 15:36 UTC, etienneburdet commented on packages/visualizations/src/components/Table/store.ts
> +export const isRtl = writable<boolean>(get(direction) === 'rtl');
Only one is needed. If we really need both, then `isRtl` is a `derived`. But we're not using `direction` anywhere.

2024-07-02 08:22 UTC, cybervinvin commented
After discussions, we decided to close this PR.
The table must use the reading direction of the page itself and the native behavior is sufficient.
New PR here: https://github.com/opendatasoft/ods-dataviz-sdk/pull/253

2024-07-02 08:22 UTC, closed without merging