Chore: add accessor to formatters
opendatasoft/ods-dataviz-sdk pull request #267
Opened 2024-12-02 14:20 UTC by etienneburdet

## Summary

The goal for this PR is to add accessor functions to table fields, in order to extract the value from a more complex datasource. Overall it decouples what we pass as `value` to what we pass to `dsiplay`. It's needed for files on the platform, will be needed to display label on geocolumns and could be used for links etc.

(Internal for Opendatasoft only) Associated Shortcut ticket: [sc-50639](https://app.shortcut.com/opendatasoft/story/feature/sc-50639/table-render-file-fields).

### Changes
The main change is to add an `accessor` functions, that transform rawValues into the value of the cell–which can now be different from it's display.
Other possibility: Tanstack table has `accessorKey` and `accessorFn` to quickly access another column. I though for our case, `accessorFn` would be general enough.

#### Breaking Changes

_describe the changes that are not backward compatible_

### Changelog

_short sentence to serve as a public changelog:_

For a bug: "We fixed a bug in the Map component: Middle-Earth's vector tiles are now available."

For a new feature: "In the Map component: It's now possible to display the route of Frodo's journey from Hobbiton to Mount Doom."

## Open discussion

_describe implementation points that you would like to discuss if any_

_describe functional behaviour that you would like to discuss if any_

## To be tested

_points that may not be obviously related to the changes but are impacted_

_special cases that are not widely known_

## Review checklist

- [ ] Description is complete
- [ ] Commits respect the [Conventional Commits Specification](https://github.com/opendatasoft/ods-dataviz-sdk/blob/main/CONTRIBUTING.md#commit-messages)
- [ ] 2 reviewers (1 if trivial)
- [ ] Tests coverage has improved
- [ ] Code is ready for a release on NPM

2024-12-03 17:25 UTC, KevinFabre-ods reviewed
I struggle to understand the difference between `display` and `accessor` for some formats
To me, it's the same thing for Boolean, Short and Long text format. 

Can't we find another wording for this property? (like `transformer`?) and only defined it where it make sense.
- DateFormat
- NumberFormat
- URLFormat
- GeoFormat

Looking at the TanStack documentation, the `accessorfn` has the record item as 1st parameter. 
So It can be used to build something like this:

```js
item => `${item.first} ${item.lastName}`
```

In our case, the `accessor` only get the raw value as parameter.
As I said early maybe the wording is not quite right.

For complex formats such as DateFormat, NumberFormat, URLFormat, or GeoFormat, it makes sense to separate how the 'label' is constructed from how the raw value is used to render a date, number, URL link, or map. 
However, something still feels off to me. Perhaps the [comment](https://github.com/opendatasoft/ods-dataviz-sdk/pull/265#discussion_r1867364885) I made earlier regarding code reorganization, particularly around type checks and warning triggers, could help make this distinction clearer.

2024-12-05 15:34 UTC, etienneburdet commented
So I changed things a bit so that: 
* A column has an accessor for its value of form `fullRecord => value`
* Options can be either an object or an accessor of form `fullRecord => optionsObject`
* Formatters don't take accessors, but some options still are function of the rawValue.
* 
* I think it makes sense to have display mutating the value after everything (or else why using a formatter?). `sources` is very likely to be a function too, since rawValue will be a shape. In all cases it's always possible to fallback. to the accessor and make things that depend on the whole record.

I changed the geosshape story a bit, so that we make use of that to label the geofield with another column. I didn't implement "hidden" column option, but that's the spirit I think.

2024-12-05 15:35 UTC, etienneburdet commented on packages/visualizations/src/components/Format/URLFormat.svelte
> +        }
I don't think we could enable it component by component if it was a store. My problem was mainly to have hundreds of warnings (10 * 10 table is 100 cell already) or none at all when using it.

2024-12-06 08:38 UTC, KevinFabre-ods reviewed
Hello, 

Could you try to update conditions where the value type is checked?
Like we agreed in https://github.com/opendatasoft/ods-dataviz-sdk/pull/265#discussion_r1867364885

2024-12-06 12:39 UTC, etienneburdet commented
Random naming though: `value/valueToString` instead of `rawValue/display` ?

2024-12-06 14:02 UTC, KevinFabre-ods commented
> Random naming though: `value/valueToString` instead of `rawValue/display` ?

Yes, that would be better.
Maybe `valueToLabel` `valueToText` is better than `valueToString` to clearly indicates that is will transform the label into something readable for a human

2024-12-09 10:16 UTC, KevinFabre-ods reviewed
Great job to extract the format logic 👍 

I agree on the data flow from the table to the format components.

- `accessor` is for a table column to override the value we pass to a format  component ✅ 
- `column.options` is either a function (that take the record data) or an object ✅ 
   - `options.rawValue` is however required 🔴  For a column table, rawValue comes from `column.key` or `column.accessor`
- In format component, most props are primitive or object. If we have props that are function that take the result of the formatting as parameter ✅ 
      
I'm also in favor to rename `rawValue`

2024-12-09 10:16 UTC, KevinFabre-ods commented on packages/visualizations/src/components/Table/types.ts
> +export type FormatPropsTypeMap = {
I got an error when I try to declare a column
`options.rawValue` shouldn't be required

![image](https://github.com/user-attachments/assets/c9b79c21-cfba-4f3e-8f4a-b3209d8b1b13)
```
Type '(r: Record<string, unknown>) => { display(v: string): string; }' is not assignable to type 'ValueOrAccessor<DateFormatProps> | undefined'.
  Type '(r: Record<string, unknown>) => { display(v: string): string; }' is not assignable to type '(r: Record<string, unknown>) => DateFormatProps'.
    Property 'rawValue' is missing in type '{ display(v: string): string; }' but required in type 'DateFormatProps'
 ```

2024-12-12 15:24 UTC, KevinFabre-ods requested changes
There are things to fixed with the debug data flow

Main issue is for me the typescript errors, as it stands, we'll get these errors too in our platform repository

2024-12-12 15:24 UTC, KevinFabre-ods commented on packages/visualizations/src/components/Format/index.ts
>      boolean: BooleanFormat,
This Format constant doesn't seem to be used somewhere. 
Do we need it in our application ?

2024-12-12 15:24 UTC, KevinFabre-ods commented on packages/visualizations/src/components/Table/types.ts
> +export type FormatPropsTypeMap = {
I still have the error. Can also see when running `npm run watch`
 > Type 'Record<string, unknown>' is not assignable to type 'Record'
 
 Shouldn't Column type be generic ?

2024-12-12 15:24 UTC, KevinFabre-ods commented on packages/visualizations/src/components/Table/types.ts
> +    options?: ValueOrAccessor<FormatPropsTypeMap[F]>;
It's better but option is still defined as any
<img width="653" alt="image" src="https://github.com/user-attachments/assets/8bd399f2-d35a-4ea7-a03b-fe365f21dfc4" />

2024-12-12 15:48 UTC, etienneburdet commented on packages/visualizations/src/components/Format/TextFormat.svelte
> +<span>{format(value)}</span>
I think we have too if we want to be able to add text-ellipsis etc. with CSS override. Maybe we have to do that as well for the other? We just didn't run into the need yet.

2024-12-12 21:24 UTC, KevinFabre-ods commented on packages/visualizations/src/components/Format/TextFormat.svelte
> +<span>{format(value)}</span>
IMO It depends on the "philosophy" we want to have here.

Do the format components only deal with the format value, or do they also set some display rules?

2024-12-17 15:59 UTC, etienneburdet commented
Ok so I fixed the options import by not using the path alias… they don't work with types between the two repos for now.

As for typing the accessor functions, I resorted to some `any`: doesn't yell at you if you don't input anything, but you can type the columns if you want. Combinations of `never ? … : ` or `R = unknown` just forced to add a generic all the way up to TableProps which was pretty alien.

2025-01-07 16:17 UTC, KevinFabre-ods commented on packages/visualizations-react/stories/Table/options.ts
> +            valueToLabel: (v: number) => `${v} words`,
```suggestion
            valueToLabel: (v: string) => `${v} words`,
```
I have a TS error: `Type 'string' is not assignable to type 'number'`

2025-01-07 16:17 UTC, KevinFabre-ods commented on packages/visualizations/src/components/Format/NumberFormat.svelte
> +            }
Still exist

We should only warn when value is not a finite number

2025-01-07 16:21 UTC, KevinFabre-ods commented on packages/visualizations/src/components/Table/Cell/utils.ts
> +};
Could you please check that some code is missing to propagate the `debugWarnings` Table prop until the format components?

2025-01-07 16:26 UTC, KevinFabre-ods commented on packages/visualizations/src/components/Table/TableCard.svelte
> +            columns={debugWarnings ? addWarnings(columns) : columns}
Currently, the only place where `addWarnings` is used will always get columns with `debugWarnings` set to false whether or not `tableOptions.debugWarnings` is either true or false

2025-01-07 16:32 UTC, KevinFabre-ods commented on packages/visualizations/src/components/Format/TextFormat.svelte
> +<span>{format(value)}</span>
Currently `TextFormat.Svelte` doesn't hold any style. 

The style definition is in `Cell.Svelte`.
What are our usage for this component outside of this package? 
If we use `TextFormat.Svelte` are we expecting some style attached to it?

2025-01-07 16:37 UTC, KevinFabre-ods commented on packages/visualizations/src/components/Format/utils.ts
> +    return value !== undefined && value !== null;
⏳

2025-01-07 16:51 UTC, KevinFabre-ods reviewed
I think we are done with all the new accessor logic. GG! 👏 

Could you please check my comments in my previous reviews, IMO we still need to resolve issues / suggestions

2025-01-07 16:51 UTC, KevinFabre-ods commented on packages/visualizations/src/components/Table/types.ts
> +    options?: ValueOrAccessor<Omit<FormatPropsTypeMap[F], 'value'>, R>;
```suggestion
    accessor?: (r: R) => FormatPropsTypeMap[F]['value'];
    options?: ValueOrAccessor<Omit<FormatPropsTypeMap[F], 'value'>, R>;
```

With that `ReturnTypeMap` can be removed

2025-01-10 13:25 UTC, KevinFabre-ods reviewed
👋 

With your latest commit, I was able to resolve some of comments.

Could you give your thoughts about the comments that are still opened ?
- debugs warning are not thrown in the console https://github.com/opendatasoft/ods-dataviz-sdk/pull/267#discussion_r1882267437
- addition of the `debugWarnings` property can be simplified. there is one ternary condition too many https://github.com/opendatasoft/ods-dataviz-sdk/pull/267#discussion_r1905742467
- Unused variables https://github.com/opendatasoft/ods-dataviz-sdk/pull/267#discussion_r1882347130
- Should the `TextFormat` have a `span` tag ? https://github.com/opendatasoft/ods-dataviz-sdk/pull/267#discussion_r1882290266

2025-01-15 08:31 UTC, KevinFabre-ods approved these changes
GG WP! 👏

2025-01-15 12:18 UTC, richterb approved these changes
The changes make sense! I added a small remark regarding the debug logger but it's minor and probably impossible to do 🙈

2025-01-15 12:18 UTC, richterb commented on package.json
> +    "nx": "^20.2.1"
In general, better to avoid upgrades (especially a major version) in a feature PR 😄 But if you tested alright and Kevin and I didn't get any issue during review either, I guess we're good

2025-01-15 12:18 UTC, richterb commented on packages/visualizations/src/components/Format/utils.ts
> +    switch (format) {
Usually I tend to add the "if (debugWarning)" in the debug function itself, so that future devs that use it don't have to remember to do the check themselves. Also it prevents having to pass `debugWarning` deep down. But I'm not sure that the store that holds the value is accessible here :/ My Svelte is rusty

2025-01-16 08:59 UTC, etienneburdet commented on package.json
> +    "nx": "^20.2.1"
It's for github actions, it crashes because nx doesn't find its arm64 or linux package… It's not the first time and I really don't know how to fix that. Maybe we should have a fixed version instead of carret 🤔

2025-01-16 09:02 UTC, etienneburdet commented on packages/visualizations/src/components/Format/utils.ts
> +    switch (format) {
We have to subscribe manually, but `debugWarnings` store could be used in utils.ts indeed. (it changes in svelte 5 with .svelte.ts files).

2025-01-16 09:28 UTC, richterb commented on package.json
> +    "nx": "^20.2.1"
Agreed. I once had a similar issue locally, and then not anymore a few days later, so that's a good probability 😬

2025-01-21 16:01 UTC, wmai approved these changes
I'm currently getting familiar with the `Table` component code, but at first glance, everything looks great 👏

I've only one small question regarding the `GeoFormat`, when `valueToLabel` is `undefined`, nothing is displayed. Is this intentional? Wouldn't it be preferable to default to displaying the coordinates as a simple string?

2025-01-24 12:19 UTC, etienneburdet commented
@wmai merging without a default for geo because as of now we pass a full maplibre style which really aweful, but also includes some variable names for sources and coordinates are children of it.

2025-01-24 12:20 UTC, merged